name: ci

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'master'
#      - 'github-action'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Checkout
        uses: actions/checkout@v2

      - name: clone libjodycode
        run: |
          git clone https://github.com/deep-soft/libjodycode libjodycode

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and push slim
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/slim.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/jdupes:latest
            ghcr.io/${{ env.OWNER_LC }}/jdupes:${{ github.ref_name }}            

      - name: Build and push alpine
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/alpine.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/jdupes:alpine
            ghcr.io/${{ env.OWNER_LC }}/jdupes:${{ github.ref_name }}-alpine
